### ISSUE TITLE
Final cleanup of Pan-India Data before sending to production map

### ISSUE THREAD

**Issue by shayantist** [reach4help/reach4help#1293]
Thanks to the efforts of our team, we've cleaned up and parsed out almost 3K leads across the states of Rajasthan, Madhya Pradesh, Maharashtra, Delhi and Uttar Pradesh in India!

Now, we need to do some final cleanup of our data here on Airtable (similar to Excel but much more powerful): https://airtable.com/invite/l?inviteId=invo0HBY830Cic1CO&inviteToken=8ce8d4b5802685667c5493f906fe35b2d63ac3cbdbbefd9b41db97cb1dca587a

Tasks: 
- [ ] Remove leads with empty fields **(Trevor)**
- [ ] Clean up/verify leads with not enough info (no contact number, no name, etc.) **(Drup, Lakshay, Jaymin's team)**
- [ ] Clean up duplicates **(Shayan)**
- [ ] Refine the "Location" field using the "Distributor Name" field **(Geena)**

You can also find a demo map live here: https://share.streamlit.io/reach4help/reach4help/map/map/parse_scripts/dashboard/data_clean_dashboard.py
![image](https://user-images.githubusercontent.com/29135917/119655878-e2184c80-be4b-11eb-9ea2-a58c9ba669eb.png)
