### ISSUE TITLE
MVP

### ISSUE THREAD

**Issue by s0** [reach4help/reach4help#310]
Details: https://app.zenhub.com/workspaces/reach4help-5e8dcbfb14ac087f410cbabb/issues/reach4help/reach4help/310

Overview of all tasks to be done, assignment and progress to get the MVP done!

## Resources

* [UX Design](https://www.lucidchart.com/documents/edit/e7b62422-f9ff-4f99-8558-ad99b56e219c/0_0?shared=true)
* [UI Design](https://www.figma.com/file/OiU7Tl4k1YFfqZQXxLaRrl/Reach4Help?node-id=220%3A120)

--------
### [ZenHub Information](https://app.zenhub.com/workspaces/reach4help-5e8dcbfb14ac087f410cbabb/issues/reach4help/reach4help/310)

*This information is updated automatically. To modify it, please use ZenHub.*

**Children:**

* [x] ~~**[EPIC]** [#312 - View: Landing Page](https://github.com/reach4help/reach4help/issues/312)~~
  * [x] ~~[#311 - design view: Get GPS](https://github.com/reach4help/reach4help/issues/311)~~
  * [x] ~~[#313 - design view: unsupported location](https://github.com/reach4help/reach4help/issues/313)~~
  * [x] ~~[#314 - design view: login with facebook](https://github.com/reach4help/reach4help/issues/314)~~
  * [x] ~~[#315 - Implement view: get gps](https://github.com/reach4help/reach4help/issues/315)~~
  * [x] ~~[#316 - Implement view: unsupported location](https://github.com/reach4help/reach4help/issues/316)~~
  * [x] ~~[#317 - Implement view: facebook login](https://github.com/reach4help/reach4help/issues/317)~~
  * [x] ~~[#318 - design view: login with facebook](https://github.com/reach4help/reach4help/issues/318)~~
  * [x] ~~[#320 - Integrate view: landing page](https://github.com/reach4help/reach4help/issues/320)~~
  * [x] ~~[#371 - Refactor GradientBackground and CenteredCard CSS to better fit mobile experience](https://github.com/reach4help/reach4help/issues/371)~~
* [x] ~~**[EPIC]** [#322 - Core Components](https://github.com/reach4help/reach4help/issues/322)~~
  * [x] ~~**[EPIC]** [#321 - Component: Layout / Header + Side Drawer](https://github.com/reach4help/reach4help/issues/321)~~
    * [x] ~~[#323 - design component: layout / header + side drawer](https://github.com/reach4help/reach4help/issues/323)~~
    * [x] ~~[#324 - implement component: layout / header + side drawer](https://github.com/reach4help/reach4help/issues/324)~~
  * [x] ~~[#350 - Build loading wrapper](https://github.com/reach4help/reach4help/issues/350)~~
  * [x] ~~[#385 - [App shell] - Add top-bar and side bar](https://github.com/reach4help/reach4help/issues/385)~~
* [x] ~~**[EPIC]** [#325 - Views: Essential Info](https://github.com/reach4help/reach4help/issues/325)~~
  * [x] ~~**[EPIC]** [#326 - View: Get Phone Number](https://github.com/reach4help/reach4help/issues/326)~~
    * [x] ~~[#295 - Integrate: Get phone number](https://github.com/reach4help/reach4help/issues/295)~~
    * [x] ~~[#98 - Implement view: get phone number](https://github.com/reach4help/reach4help/issues/98)~~
    * [x] ~~[#338 - Design View: Get phone number](https://github.com/reach4help/reach4help/issues/338)~~
    * [x] ~~[#339 - Design View: sending confirmation code](https://github.com/reach4help/reach4help/issues/339)~~
    * [x] ~~[#340 - Implement view: sending confirmation code](https://github.com/reach4help/reach4help/issues/340)~~
    * [x] ~~[#341 - Design view: enter confirmation code](https://github.com/reach4help/reach4help/issues/341)~~
  * [x] ~~**[EPIC]** [#327 - View: Name & Address](https://github.com/reach4help/reach4help/issues/327)~~
    * [x] ~~[#100 - Implement view: Name & Address](https://github.com/reach4help/reach4help/issues/100)~~
    * [x] ~~[#344 - Design view: Name & address](https://github.com/reach4help/reach4help/issues/344)~~
  * [x] ~~**[EPIC]** [#328 - View: Role Info](https://github.com/reach4help/reach4help/issues/328)~~
    * [x] ~~[#345 - Design View: Role Info](https://github.com/reach4help/reach4help/issues/345)~~
  * [x] ~~[#383 - [Personal-Data] - Add geolocation functionality](https://github.com/reach4help/reach4help/issues/383)~~
  * [x] ~~[#384 - [Personal-data] - Add user info from firebase to form](https://github.com/reach4help/reach4help/issues/384)~~
* [ ] **[EPIC]** [#329 - Views: PIN Flow](https://github.com/reach4help/reach4help/issues/329)
  * [ ] **[EPIC]** [#330 - View: PIN: Request something new](https://github.com/reach4help/reach4help/issues/330)
    * [x] ~~[#162 - [New Request] - Add new request screen](https://github.com/reach4help/reach4help/issues/162)~~
    * [x] ~~[#346 - Design view: PIN: Request something new](https://github.com/reach4help/reach4help/issues/346)~~
    * [x] ~~[#386 - [New Request] - Add "request created" page](https://github.com/reach4help/reach4help/issues/386)~~
  * [x] ~~**[EPIC]** [#331 - View: PIN: Request created screen (please wait)](https://github.com/reach4help/reach4help/issues/331)~~
    * [x] ~~[#347 - Design view: PIN: Request created (please wait)](https://github.com/reach4help/reach4help/issues/347)~~
    * [x] ~~[#348 - Implement View: PIN: Request created screen (please wait)](https://github.com/reach4help/reach4help/issues/348)~~
  * [x] ~~**[EPIC]** [#332 - View: PIN: My Requests](https://github.com/reach4help/reach4help/issues/332)~~
    * [x] ~~[#102 - Implement View: PIN: My Requests](https://github.com/reach4help/reach4help/issues/102)~~
    * [x] ~~[#353 - Design View: PIN: My Requests](https://github.com/reach4help/reach4help/issues/353)~~
  * [x] ~~**[EPIC]** [#333 - View: PIN: Request Details](https://github.com/reach4help/reach4help/issues/333)~~
    * [x] ~~[#160 - Implement Mobile View: PIN: Request Details](https://github.com/reach4help/reach4help/issues/160)~~
    * [x] ~~[#354 - Design Mobile View: PIN: Request Details](https://github.com/reach4help/reach4help/issues/354)~~
  * [x] ~~**[EPIC]** [#334 - View: PIN: Accept / Reject Request](https://github.com/reach4help/reach4help/issues/334)~~
    * [x] ~~[#161 - Implement View: Volunteer offers (Accept / Reject Request)](https://github.com/reach4help/reach4help/issues/161)~~
    * [x] ~~[#355 - Design Mobile View: Accept / Reject Request](https://github.com/reach4help/reach4help/issues/355)~~
  * [x] ~~**[EPIC]** [#335 - View: PIN: PIN rating CAV](https://github.com/reach4help/reach4help/issues/335)~~
    * [x] ~~[#356 - Design Mobile View: PIN: rating CAV](https://github.com/reach4help/reach4help/issues/356)~~
    * [x] ~~[#357 - Implement Modal View: PIN: rating CAV](https://github.com/reach4help/reach4help/issues/357)~~
* [ ] **[EPIC]** [[@telmodias](https://github.com/telmodias)] [#337 - Views: CAV Flow](https://github.com/reach4help/reach4help/issues/337)
  * [x] ~~[#336 - Complete UX flow for CAV](https://github.com/reach4help/reach4help/issues/336)~~
  * [x] ~~[#395 - Create UI + Frontend tickets for all CAV Views once UX is ready](https://github.com/reach4help/reach4help/issues/395)~~
  * [x] ~~**[EPIC]** [#449 - CAV Flow View #1: Sidemenu + Navbar](https://github.com/reach4help/reach4help/issues/449)~~
    * [x] ~~[#450 - UI of CAV Flow View #1: Sidemenu + Navbar](https://github.com/reach4help/reach4help/issues/450)~~
    * [x] ~~[#451 - Frontend of CAV Flow View #1: Sidemenu + Navbar](https://github.com/reach4help/reach4help/issues/451)~~
    * [x] ~~[#465 - Firebase for CAV Flow View #1: Sidemenu + Navbar](https://github.com/reach4help/reach4help/issues/465)~~
  * [x] ~~**[EPIC]** [#452 - CAV Flow View #2: Timeline](https://github.com/reach4help/reach4help/issues/452)~~
    * [x] ~~[#453 - UI of CAV Flow View #2: Timeline](https://github.com/reach4help/reach4help/issues/453)~~
    * [x] ~~[#454 - Frontend of CAV Flow View #2: Timeline](https://github.com/reach4help/reach4help/issues/454)~~
    * [x] ~~[#464 - Firebase for CAV Flow View #2: Timeline](https://github.com/reach4help/reach4help/issues/464)~~
  * [x] ~~**[EPIC]** [#455 - CAV Flow View #3: Requests](https://github.com/reach4help/reach4help/issues/455)~~
    * [x] ~~[#456 - UI of CAV Flow View #3: Requests](https://github.com/reach4help/reach4help/issues/456)~~
    * [x] ~~[#457 - Frontend of CAV Flow View #3: Requests](https://github.com/reach4help/reach4help/issues/457)~~
    * [x] ~~[#463 - Firebase of CAV Flow View #3: Requests](https://github.com/reach4help/reach4help/issues/463)~~
  * [x] ~~**[EPIC]** [#459 - CAV Flow View #4: Map](https://github.com/reach4help/reach4help/issues/459)~~
    * [x] ~~[#460 - UI of CAV Flow View #4: Map](https://github.com/reach4help/reach4help/issues/460)~~
    * [x] ~~[#461 - Frontend of CAV Flow View #4: Map](https://github.com/reach4help/reach4help/issues/461)~~
    * [x] ~~[#462 - Firebase for CAV Flow View #4: Map](https://github.com/reach4help/reach4help/issues/462)~~
* [ ] **[EPIC]** [[@sabind](https://github.com/sabind)] [#359 - Complete backend for MVP](https://github.com/reach4help/reach4help/issues/359)
  * [x] ~~[#278 - When an offer status is changed to `accepted` the associated request needs to be updated](https://github.com/reach4help/reach4help/issues/278)~~
  * [x] ~~[#279 - When the status of a request is updated a `timeline_item` record should be created.](https://github.com/reach4help/reach4help/issues/279)~~
  * [ ] [#280 - If the CAV cancels their offer we should make sure to clean up all necessary data.](https://github.com/reach4help/reach4help/issues/280)
  * [ ] [#281 - When a user completes a questionnaire update the questionnaire ref in the user object.](https://github.com/reach4help/reach4help/issues/281)
  * [ ] **[EPIC]** [[@sabind](https://github.com/sabind)] [#358 - Create required rules for firestore](https://github.com/reach4help/reach4help/issues/358)
    * [ ] [#273 - Modifying or creating a user record (and associated sub collections) should be restricted to authenticated users with a matching authentication id.](https://github.com/reach4help/reach4help/issues/273)
    * [ ] [#274 - Only authenticated users who have completed the PIN Questionnaire should be able to create requests.](https://github.com/reach4help/reach4help/issues/274)
    * [x] ~~[#275 - Only users who's ID matches the PIN Reference in a Request should be able to edit the request.](https://github.com/reach4help/reach4help/issues/275)~~
    * [x] ~~[#276 - Only authenticated users who's user id matches the PIN User Ref of a Request should be able to access the offers sub collection.](https://github.com/reach4help/reach4help/issues/276)~~
    * [ ] [#277 - Only authenticated users who have completed the CAV Questionnaire should be allowed to submit request offers.](https://github.com/reach4help/reach4help/issues/277)
    * [ ] [#282 - A user may only create each questionnaire once.](https://github.com/reach4help/reach4help/issues/282)
    * [x] ~~[#283 - A user may only update their own questionnaires](https://github.com/reach4help/reach4help/issues/283)~~
* [ ] **[EPIC]** [#361 - Complete Shared Backend & Frontend code for MVP](https://github.com/reach4help/reach4help/issues/361)
  * [x] ~~[#231 - Setting up Firebase auth (just Facebook login for MVP)](https://github.com/reach4help/reach4help/issues/231)~~
  * [ ] [[@s0](https://github.com/s0)] [#253 - Migrate data model from functions to own package in monorepo so it can be used in frontend](https://github.com/reach4help/reach4help/issues/253)

**Comment by isma-osy** [comment]
Moved to Icebox to be able to use zenhub as our clean unique project management tool
