### ISSUE TITLE
View: Landing Page

### ISSUE THREAD

**Issue by s0** [reach4help/reach4help#312]
--------
### [ZenHub Information](https://app.zenhub.com/workspaces/reach4help-5e8dcbfb14ac087f410cbabb/issues/reach4help/reach4help/312)

*This information is updated automatically. To modify it, please use ZenHub.*

**Belonging to Epics:**

* **[EPIC]** [#310 - MVP](https://github.com/reach4help/reach4help/issues/310)

**Children:**

* [x] ~~[#311 - design view: Get GPS](https://github.com/reach4help/reach4help/issues/311)~~
* [x] ~~[#313 - design view: unsupported location](https://github.com/reach4help/reach4help/issues/313)~~
* [x] ~~[#314 - design view: login with facebook](https://github.com/reach4help/reach4help/issues/314)~~
* [x] ~~[#315 - Implement view: get gps](https://github.com/reach4help/reach4help/issues/315)~~
* [x] ~~[#316 - Implement view: unsupported location](https://github.com/reach4help/reach4help/issues/316)~~
* [x] ~~[#317 - Implement view: facebook login](https://github.com/reach4help/reach4help/issues/317)~~
* [x] ~~[#318 - design view: login with facebook](https://github.com/reach4help/reach4help/issues/318)~~
* [x] ~~[#320 - Integrate view: landing page](https://github.com/reach4help/reach4help/issues/320)~~
* [x] ~~[#371 - Refactor GradientBackground and CenteredCard CSS to better fit mobile experience](https://github.com/reach4help/reach4help/issues/371)~~
