### ISSUE TITLE
Core Components

### ISSUE THREAD

**Issue by s0** [reach4help/reach4help#322]
--------
### [ZenHub Information](https://app.zenhub.com/workspaces/reach4help-5e8dcbfb14ac087f410cbabb/issues/reach4help/reach4help/322)

*This information is updated automatically. To modify it, please use ZenHub.*

**Belonging to Epics:**

* **[EPIC]** [#310 - MVP](https://github.com/reach4help/reach4help/issues/310)

**Children:**

* [x] ~~**[EPIC]** [#321 - Component: Layout / Header + Side Drawer](https://github.com/reach4help/reach4help/issues/321)~~
  * [x] ~~[#323 - design component: layout / header + side drawer](https://github.com/reach4help/reach4help/issues/323)~~
  * [x] ~~[#324 - implement component: layout / header + side drawer](https://github.com/reach4help/reach4help/issues/324)~~
* [x] ~~[#350 - Build loading wrapper](https://github.com/reach4help/reach4help/issues/350)~~
* [x] ~~[#385 - [App shell] - Add top-bar and side bar](https://github.com/reach4help/reach4help/issues/385)~~
