### ISSUE TITLE
Views: Essential Info

### ISSUE THREAD

**Issue by s0** [reach4help/reach4help#325]
--------
### [ZenHub Information](https://app.zenhub.com/workspaces/reach4help-5e8dcbfb14ac087f410cbabb/issues/reach4help/reach4help/325)

*This information is updated automatically. To modify it, please use ZenHub.*

**Belonging to Epics:**

* **[EPIC]** [#310 - MVP](https://github.com/reach4help/reach4help/issues/310)

**Children:**

* [x] ~~**[EPIC]** [#326 - View: Get Phone Number](https://github.com/reach4help/reach4help/issues/326)~~
  * [x] ~~[#295 - Integrate: Get phone number](https://github.com/reach4help/reach4help/issues/295)~~
  * [x] ~~[#98 - Implement view: get phone number](https://github.com/reach4help/reach4help/issues/98)~~
  * [x] ~~[#338 - Design View: Get phone number](https://github.com/reach4help/reach4help/issues/338)~~
  * [x] ~~[#339 - Design View: sending confirmation code](https://github.com/reach4help/reach4help/issues/339)~~
  * [x] ~~[#340 - Implement view: sending confirmation code](https://github.com/reach4help/reach4help/issues/340)~~
  * [x] ~~[#341 - Design view: enter confirmation code](https://github.com/reach4help/reach4help/issues/341)~~
* [x] ~~**[EPIC]** [#327 - View: Name & Address](https://github.com/reach4help/reach4help/issues/327)~~
  * [ ] [#100 - Implement view: Name & Address](https://github.com/reach4help/reach4help/issues/100)
  * [x] ~~[#344 - Design view: Name & address](https://github.com/reach4help/reach4help/issues/344)~~
* [x] ~~**[EPIC]** [#328 - View: Role Info](https://github.com/reach4help/reach4help/issues/328)~~
  * [x] ~~[#345 - Design View: Role Info](https://github.com/reach4help/reach4help/issues/345)~~
* [x] ~~[#383 - [Personal-Data] - Add geolocation functionality](https://github.com/reach4help/reach4help/issues/383)~~
* [x] ~~[#384 - [Personal-data] - Add user info from firebase to form](https://github.com/reach4help/reach4help/issues/384)~~
