### ISSUE TITLE
View: Get Phone Number

### ISSUE THREAD

**Issue by s0** [reach4help/reach4help#326]
--------
### [ZenHub Information](https://app.zenhub.com/workspaces/reach4help-5e8dcbfb14ac087f410cbabb/issues/reach4help/reach4help/326)

*This information is updated automatically. To modify it, please use ZenHub.*

**Belonging to Epics:**

* **[EPIC]** [#325 - Views: Essential Info](https://github.com/reach4help/reach4help/issues/325)

**Children:**

* [x] ~~[#295 - Integrate: Get phone number](https://github.com/reach4help/reach4help/issues/295)~~
* [x] ~~[#98 - Implement view: get phone number](https://github.com/reach4help/reach4help/issues/98)~~
* [x] ~~[#338 - Design View: Get phone number](https://github.com/reach4help/reach4help/issues/338)~~
* [x] ~~[#339 - Design View: sending confirmation code](https://github.com/reach4help/reach4help/issues/339)~~
* [x] ~~[#340 - Implement view: sending confirmation code](https://github.com/reach4help/reach4help/issues/340)~~
* [x] ~~[#341 - Design view: enter confirmation code](https://github.com/reach4help/reach4help/issues/341)~~
