### ISSUE TITLE
Views: PIN Flow

### ISSUE THREAD

**Issue by s0** [reach4help/reach4help#329]
--------
### [ZenHub Information](https://app.zenhub.com/workspaces/reach4help-5e8dcbfb14ac087f410cbabb/issues/reach4help/reach4help/329)

*This information is updated automatically. To modify it, please use ZenHub.*

**Belonging to Epics:**

* ~~**[EPIC]** [#310 - MVP](https://github.com/reach4help/reach4help/issues/310)~~

**Children:**

* [ ] **[EPIC]** [#330 - View: PIN: Request something new](https://github.com/reach4help/reach4help/issues/330)
  * [x] ~~[#162 - [New Request] - Add new request screen](https://github.com/reach4help/reach4help/issues/162)~~
  * [x] ~~[#346 - Design view: PIN: Request something new](https://github.com/reach4help/reach4help/issues/346)~~
  * [x] ~~[#386 - [New Request] - Add "request created" page](https://github.com/reach4help/reach4help/issues/386)~~
* [x] ~~**[EPIC]** [#331 - View: PIN: Request created screen (please wait)](https://github.com/reach4help/reach4help/issues/331)~~
  * [x] ~~[#347 - Design view: PIN: Request created (please wait)](https://github.com/reach4help/reach4help/issues/347)~~
  * [x] ~~[#348 - Implement View: PIN: Request created screen (please wait)](https://github.com/reach4help/reach4help/issues/348)~~
* [x] ~~**[EPIC]** [#332 - View: PIN: My Requests](https://github.com/reach4help/reach4help/issues/332)~~
  * [x] ~~[#102 - Implement View: PIN: My Requests](https://github.com/reach4help/reach4help/issues/102)~~
  * [x] ~~[#353 - Design View: PIN: My Requests](https://github.com/reach4help/reach4help/issues/353)~~
* [x] ~~**[EPIC]** [#333 - View: PIN: Request Details](https://github.com/reach4help/reach4help/issues/333)~~
  * [x] ~~[#160 - Implement Mobile View: PIN: Request Details](https://github.com/reach4help/reach4help/issues/160)~~
  * [x] ~~[#354 - Design Mobile View: PIN: Request Details](https://github.com/reach4help/reach4help/issues/354)~~
* [x] ~~**[EPIC]** [#334 - View: PIN: Accept / Reject Request](https://github.com/reach4help/reach4help/issues/334)~~
  * [x] ~~[#161 - Implement View: Volunteer offers (Accept / Reject Request)](https://github.com/reach4help/reach4help/issues/161)~~
  * [x] ~~[#355 - Design Mobile View: Accept / Reject Request](https://github.com/reach4help/reach4help/issues/355)~~
* [x] ~~**[EPIC]** [#335 - View: PIN: PIN rating CAV](https://github.com/reach4help/reach4help/issues/335)~~
  * [x] ~~[#356 - Design Mobile View: PIN: rating CAV](https://github.com/reach4help/reach4help/issues/356)~~
  * [x] ~~[#357 - Implement Modal View: PIN: rating CAV](https://github.com/reach4help/reach4help/issues/357)~~
