### ISSUE TITLE
View: PIN: Request something new

### ISSUE THREAD

**Issue by s0** [reach4help/reach4help#330]
--------
### [ZenHub Information](https://app.zenhub.com/workspaces/reach4help-5e8dcbfb14ac087f410cbabb/issues/reach4help/reach4help/330)

*This information is updated automatically. To modify it, please use ZenHub.*

**Belonging to Epics:**

* **[EPIC]** [#329 - Views: PIN Flow](https://github.com/reach4help/reach4help/issues/329)

**Children:**

* [x] ~~[#162 - [New Request] - Add new request screen](https://github.com/reach4help/reach4help/issues/162)~~
* [x] ~~[#346 - Design view: PIN: Request something new](https://github.com/reach4help/reach4help/issues/346)~~
* [x] ~~[#386 - [New Request] - Add "request created" page](https://github.com/reach4help/reach4help/issues/386)~~
