### ISSUE TITLE
Views: CAV Flow

### ISSUE THREAD

**Issue by s0** [reach4help/reach4help#337]
We need to have UX complete before we can detail the remaining views

--------
### [ZenHub Information](https://app.zenhub.com/workspaces/reach4help-5e8dcbfb14ac087f410cbabb/issues/reach4help/reach4help/337)

*This information is updated automatically. To modify it, please use ZenHub.*

**Belonging to Epics:**

* ~~**[EPIC]** [#310 - MVP](https://github.com/reach4help/reach4help/issues/310)~~

**Children:**

* [x] ~~[#336 - Complete UX flow for CAV](https://github.com/reach4help/reach4help/issues/336)~~
* [x] ~~[#395 - Create UI + Frontend tickets for all CAV Views once UX is ready](https://github.com/reach4help/reach4help/issues/395)~~
* [x] ~~**[EPIC]** [#449 - CAV Flow View #1: Sidemenu + Navbar](https://github.com/reach4help/reach4help/issues/449)~~
  * [x] ~~[#450 - UI of CAV Flow View #1: Sidemenu + Navbar](https://github.com/reach4help/reach4help/issues/450)~~
  * [x] ~~[#451 - Frontend of CAV Flow View #1: Sidemenu + Navbar](https://github.com/reach4help/reach4help/issues/451)~~
  * [x] ~~[#465 - Firebase for CAV Flow View #1: Sidemenu + Navbar](https://github.com/reach4help/reach4help/issues/465)~~
* [x] ~~**[EPIC]** [#452 - CAV Flow View #2: Timeline](https://github.com/reach4help/reach4help/issues/452)~~
  * [x] ~~[#453 - UI of CAV Flow View #2: Timeline](https://github.com/reach4help/reach4help/issues/453)~~
  * [x] ~~[#454 - Frontend of CAV Flow View #2: Timeline](https://github.com/reach4help/reach4help/issues/454)~~
  * [x] ~~[#464 - Firebase for CAV Flow View #2: Timeline](https://github.com/reach4help/reach4help/issues/464)~~
* [x] ~~**[EPIC]** [#455 - CAV Flow View #3: Requests](https://github.com/reach4help/reach4help/issues/455)~~
  * [x] ~~[#456 - UI of CAV Flow View #3: Requests](https://github.com/reach4help/reach4help/issues/456)~~
  * [x] ~~[#457 - Frontend of CAV Flow View #3: Requests](https://github.com/reach4help/reach4help/issues/457)~~
  * [x] ~~[#463 - Firebase of CAV Flow View #3: Requests](https://github.com/reach4help/reach4help/issues/463)~~
* [x] ~~**[EPIC]** [#459 - CAV Flow View #4: Map](https://github.com/reach4help/reach4help/issues/459)~~
  * [x] ~~[#460 - UI of CAV Flow View #4: Map](https://github.com/reach4help/reach4help/issues/460)~~
  * [x] ~~[#461 - Frontend of CAV Flow View #4: Map](https://github.com/reach4help/reach4help/issues/461)~~
  * [x] ~~[#462 - Firebase for CAV Flow View #4: Map](https://github.com/reach4help/reach4help/issues/462)~~
