### ISSUE TITLE
Create required rules for firestore

### ISSUE THREAD

**Issue by s0** [reach4help/reach4help#358]
--------
### [ZenHub Information](https://app.zenhub.com/workspaces/reach4help-5e8dcbfb14ac087f410cbabb/issues/reach4help/reach4help/358)

*This information is updated automatically. To modify it, please use ZenHub.*

**Belonging to Epics:**

* **[EPIC]** [[@sabind](https://github.com/sabind)] [#359 - Complete backend for MVP](https://github.com/reach4help/reach4help/issues/359)

**Children:**

* [ ] [#273 - Modifying or creating a user record (and associated sub collections) should be restricted to authenticated users with a matching authentication id.](https://github.com/reach4help/reach4help/issues/273)
* [ ] [#274 - Only authenticated users who have completed the PIN Questionnaire should be able to create requests.](https://github.com/reach4help/reach4help/issues/274)
* [x] ~~[#275 - Only users who's ID matches the PIN Reference in a Request should be able to edit the request.](https://github.com/reach4help/reach4help/issues/275)~~
* [x] ~~[#276 - Only authenticated users who's user id matches the PIN User Ref of a Request should be able to access the offers sub collection.](https://github.com/reach4help/reach4help/issues/276)~~
* [ ] [#277 - Only authenticated users who have completed the CAV Questionnaire should be allowed to submit request offers.](https://github.com/reach4help/reach4help/issues/277)
* [ ] [#282 - A user may only create each questionnaire once.](https://github.com/reach4help/reach4help/issues/282)
* [x] ~~[#283 - A user may only update their own questionnaires](https://github.com/reach4help/reach4help/issues/283)~~
