### ISSUE TITLE
[MAP] (task list) Communication plan for launch

### ISSUE THREAD

**Issue by isma-osy** [reach4help/reach4help#405]
- [x] Identify from Reach4Help who can help deliver the messages: volunteers assigned to the PR / social media teams or Work locally or all of these options

- [x] Use AIRTABLE as a CRM and to keep track of interactions in order to leverage knowledge later

- [ ] Ensure developers have a link to add data to the map
==> if no better option, use: https://github.com/reach4help/reach4help/tree/master/map/src/data

- [ ] Validation of the "Messages to deliver " by team (see google doc below)

- [ ] Execute the plan!

More info here:
https://docs.google.com/document/d/1H6BpARjK1GQxGOR5_AbNG4vYmxo0eTqjHUO-hX3gB8w/edit#

--------
### [ZenHub Information](https://app.zenhub.com/workspaces/reach4help-5e8dcbfb14ac087f410cbabb/issues/reach4help/reach4help/405)

*This information is updated automatically. To modify it, please use ZenHub.*

**Belonging to Epics:**

* **[EPIC]** [[@isma-osy](https://github.com/isma-osy)] [#413 - Prepare MAP for Go-To-Market / Marketing strategy](https://github.com/reach4help/reach4help/issues/413)

--------
### [ZenHub Information](https://app.zenhub.com/workspaces/reach4help-5e8dcbfb14ac087f410cbabb/issues/reach4help/reach4help/405)

*This information is updated automatically. To modify it, please use ZenHub.*

**Belonging to Epics:**

* **[EPIC]** [[@isma-osy](https://github.com/isma-osy)] [#413 - Prepare MAP for Go-To-Market / Marketing strategy](https://github.com/reach4help/reach4help/issues/413)

**Comment by isma-osy** [comment]
@s0 : can you mention during next leads meeting : we need to validate the messages to deliver to each audience?
Also is the link provided for developers still relevant given the user-friendly data adding feature being implemented ?

**Comment by s0** [comment]
Sure, i'll do that today.

And no, that data will change very shortly, hopefully by the end of the week! :)
