### ISSUE TITLE
Prepare MAP for Go-To-Market / Marketing strategy

### ISSUE THREAD

**Issue by s0** [reach4help/reach4help#413]
Ahead of the marketing effort that @isma-osy is leading for the Map, there are a few tasks that need to be completed to make it ready to for wider sharing, and for an influx of users. This epic is to track that preparation

--------
### [ZenHub Information](https://app.zenhub.com/workspaces/reach4help-5e8dcbfb14ac087f410cbabb/issues/reach4help/reach4help/413)

*This information is updated automatically. To modify it, please use ZenHub.*

**Children:**

* [x] ~~[#75 - Make Map UI Responsive](https://github.com/reach4help/reach4help/issues/75)~~
* [x] ~~[#76 - Add localization/internationalization to Map project](https://github.com/reach4help/reach4help/issues/76)~~
* [x] ~~[#286 - Allow users to submit a new marker by drawing directly on the map and filling in info](https://github.com/reach4help/reach4help/issues/286)~~
* [x] ~~[#291 - Add google analytics to map with cookie consent](https://github.com/reach4help/reach4help/issues/291)~~
* [ ] [[@isma-osy](https://github.com/isma-osy), [@s0](https://github.com/s0)] [#405 - [MAP] (task list) Communication plan for launch](https://github.com/reach4help/reach4help/issues/405)
* [x] ~~[#406 - feat(map): allow users to submit info](https://github.com/reach4help/reach4help/pull/406)~~
* [x] ~~[#408 - [MAP] Design - view](https://github.com/reach4help/reach4help/issues/408)~~
* [x] ~~[#414 - [MAP] Rework model for markers](https://github.com/reach4help/reach4help/issues/414)~~
* [ ] [[@s0](https://github.com/s0)] [#415 - [MAP] Redirect users to existing other maps / directories when appropriate](https://github.com/reach4help/reach4help/issues/415)
* [x] ~~[#416 - [MAP] Create a landing page](https://github.com/reach4help/reach4help/issues/416)~~
* [x] ~~[#427 - [MAP] design logo](https://github.com/reach4help/reach4help/issues/427)~~
