### ISSUE TITLE
CAV Flow View #1: Sidemenu + Navbar

### ISSUE THREAD

**Issue by ZiyangGao1028** [reach4help/reach4help#449]
This is the parent ticket of CAV Flow "Sidemenu + Navbar" view.

![Screen Shot 2020-04-22 at 8.10.03 PM.png](https://images.zenhubusercontent.com/5e9f44c44d7b4947cc6b5e0a/8c4ff113-6735-4af1-abd8-e88c3082b02a)

--------
### [ZenHub Information](https://app.zenhub.com/workspaces/reach4help-5e8dcbfb14ac087f410cbabb/issues/reach4help/reach4help/449)

*This information is updated automatically. To modify it, please use ZenHub.*

**Belonging to Epics:**

* **[EPIC]** [#337 - Views: CAV Flow](https://github.com/reach4help/reach4help/issues/337)

**Children:**

* [ ] [#450 - UI of CAV Flow View #1: Sidemenu + Navbar](https://github.com/reach4help/reach4help/issues/450)
* [ ] [#451 - Frontend of CAV Flow View #1: Sidemenu + Navbar](https://github.com/reach4help/reach4help/issues/451)
* [ ] [#465 - Firebase for CAV Flow View #1: Sidemenu + Navbar](https://github.com/reach4help/reach4help/issues/465)

--------
### [ZenHub Information](https://app.zenhub.com/workspaces/reach4help-5e8dcbfb14ac087f410cbabb/issues/reach4help/reach4help/449)

*This information is updated automatically. To modify it, please use ZenHub.*

**Belonging to Epics:**

* **[EPIC]** [[@telmodias](https://github.com/telmodias)] [#337 - Views: CAV Flow](https://github.com/reach4help/reach4help/issues/337)

**Children:**

* [x] ~~[#450 - UI of CAV Flow View #1: Sidemenu + Navbar](https://github.com/reach4help/reach4help/issues/450)~~
* [x] ~~[#451 - Frontend of CAV Flow View #1: Sidemenu + Navbar](https://github.com/reach4help/reach4help/issues/451)~~
* [x] ~~[#465 - Firebase for CAV Flow View #1: Sidemenu + Navbar](https://github.com/reach4help/reach4help/issues/465)~~
