### ISSUE TITLE
CAV Flow View #2: Timeline

### ISSUE THREAD

**Issue by ZiyangGao1028** [reach4help/reach4help#452]
This is the parent ticket of CAV Flow "Timeline" view.

![Screen Shot 2020-04-22 at 8.26.13 PM.png](https://images.zenhubusercontent.com/5e9f44c44d7b4947cc6b5e0a/444afebf-ccc0-4f62-b1ad-fe478462e42a)

--------
### [ZenHub Information](https://app.zenhub.com/workspaces/reach4help-5e8dcbfb14ac087f410cbabb/issues/reach4help/reach4help/452)

*This information is updated automatically. To modify it, please use ZenHub.*

**Belonging to Epics:**

* **[EPIC]** [[@telmodias](https://github.com/telmodias)] [#337 - Views: CAV Flow](https://github.com/reach4help/reach4help/issues/337)

**Children:**

* [x] ~~[#453 - UI of CAV Flow View #2: Timeline](https://github.com/reach4help/reach4help/issues/453)~~
* [x] ~~[#454 - Frontend of CAV Flow View #2: Timeline](https://github.com/reach4help/reach4help/issues/454)~~
* [x] ~~[#464 - Firebase for CAV Flow View #2: Timeline](https://github.com/reach4help/reach4help/issues/464)~~
