### ISSUE TITLE
CAV Flow View #3: Requests

### ISSUE THREAD

**Issue by ZiyangGao1028** [reach4help/reach4help#455]
This is the parent ticket of CAV Flow "Request" view.

![Screen Shot 2020-04-22 at 8.49.36 PM.png](https://images.zenhubusercontent.com/5e9f44c44d7b4947cc6b5e0a/c756cea3-8ba7-4cdf-8acd-7af81de6400b)

--------
### [ZenHub Information](https://app.zenhub.com/workspaces/reach4help-5e8dcbfb14ac087f410cbabb/issues/reach4help/reach4help/455)

*This information is updated automatically. To modify it, please use ZenHub.*

**Belonging to Epics:**

* **[EPIC]** [[@telmodias](https://github.com/telmodias)] [#337 - Views: CAV Flow](https://github.com/reach4help/reach4help/issues/337)

**Children:**

* [x] ~~[#456 - UI of CAV Flow View #3: Requests](https://github.com/reach4help/reach4help/issues/456)~~
* [x] ~~[#457 - Frontend of CAV Flow View #3: Requests](https://github.com/reach4help/reach4help/issues/457)~~
* [x] ~~[#463 - Firebase of CAV Flow View #3: Requests](https://github.com/reach4help/reach4help/issues/463)~~
