### ISSUE TITLE
CAV Flow View #4: Map

### ISSUE THREAD

**Issue by ZiyangGao1028** [reach4help/reach4help#459]
This is the parent ticket of CAV Flow "Map" view.

![Screen Shot 2020-04-22 at 8.57.56 PM.png](https://images.zenhubusercontent.com/5e9f44c44d7b4947cc6b5e0a/23d2faa8-6232-4aae-beb4-3c3f7d48a6d4)

--------
### [ZenHub Information](https://app.zenhub.com/workspaces/reach4help-5e8dcbfb14ac087f410cbabb/issues/reach4help/reach4help/459)

*This information is updated automatically. To modify it, please use ZenHub.*

**Belonging to Epics:**

* **[EPIC]** [[@telmodias](https://github.com/telmodias)] [#337 - Views: CAV Flow](https://github.com/reach4help/reach4help/issues/337)

**Children:**

* [x] ~~[#460 - UI of CAV Flow View #4: Map](https://github.com/reach4help/reach4help/issues/460)~~
* [ ] [#461 - Frontend of CAV Flow View #4: Map](https://github.com/reach4help/reach4help/issues/461)
* [ ] [#462 - Firebase for CAV Flow View #4: Map](https://github.com/reach4help/reach4help/issues/462)

**Comment by mcverter** [comment]
Design Elements:
(1) MAP
Map
Pointer Icon on the bottom toolbar and on the Map
(2) REQUEST SUMMARY
 Headline
Text Summary
 Requester Profile Image
(3) FULL REQUEST
 Profile Data
 * * Name / request date. stars. distance
 Request Data
 ** Headline
 ** Full text of Request
Volunteer UI
 ** Input Text
 ** Submit Button
