### ISSUE TITLE
[WEB-CLIENT] Sign-up simplification and usability upgrade

### ISSUE THREAD

**Issue by isma-osy** [reach4help/reach4help#804]
**Context**
After launching the MVP on June 13th many users gave us the feedback that the app asks for too much information from the beginning : using Facebook sign-up and requesting personal information such as phone and adress from the first screens.
To make the sign-up process clearer, we need to make some much-needed design and clarity fixes.

**Purpose:** 
Minimize number of screens and information requested from the user

**Solution:**
The solution includes multiple features to simplify the process for the user, making it easier to register to the app :
1-Offer 3 ways of signing-up:

- Facebook account
- Google account
- Name and email : to sign-up, the user would need to confirm his email adress by clicking a link sent to his email #788

2-Offer explanations : "what we do with the social media account / email ?" on a question and answer form
The question is something you can click on to show a dialog box with the explanation (shown above as 'Why X'). It must be an overlay on top of the screen before it.

3-Request the phone number once the user has seen the app :
A-as a PIN when he confirms his first request #789
B-as a CAV when he answers his first request #790

4-Offer explanations : "what we do with the phone number?" on a question and answer form
The question is something you can click on to show a dialog box with the explanation (shown above as 'Why X'). It must be an overlay on top of the screen before it.
Due to us requiring personal information such as a phone number and a personal social media account, we need to add a question-and-answer section under each of the personal-info screens explaining why we're asking for this info.

--------
### [ZenHub Information](https://app.zenhub.com/workspaces/reach4help-5e8dcbfb14ac087f410cbabb/issues/reach4help/reach4help/804)

*This information is updated automatically. To modify it, please use ZenHub.*

**Children:**

* [x] ~~[#788 - [WEB-CLIENT] Email sign-up](https://github.com/reach4help/reach4help/issues/788)~~
* [ ] [[@ashwinkjoseph](https://github.com/ashwinkjoseph), [@btuerker](https://github.com/btuerker)] [#789 - [WEB-CLIENT] As a new PIN, I want to provide my phone number when submitting my first request, to get to know the app first](https://github.com/reach4help/reach4help/issues/789)
* [ ] [[@ashwinkjoseph](https://github.com/ashwinkjoseph), [@btuerker](https://github.com/btuerker)] [#790 - [WEB-CLIENT] As a new CAV, I want to provide my phone number when answering my first request, to get to know the app first](https://github.com/reach4help/reach4help/issues/790)
