### ISSUE TITLE
Publish articles to Medium 

### ISSUE THREAD

**Issue by schowdhury8** [reach4help/reach4help#876]
**Description**
As per our discussion last week, we decided to use Medium as a platform to create our blog on (we can also do the same when it's time to make our own website blog). 

Well, we now have a Medium blog here: https://medium.com/@reach4help !
Everyone with access to info@reach4help.org can log into it and start writing and posting articles to it. 

We should start posting our marketing materials as well as newsletter articles onto it, so we can spread it easier and gain some recognition in the cyberspace.  

--------
### [ZenHub Information](https://app.zenhub.com/workspaces/reach4help-5e8dcbfb14ac087f410cbabb/issues/reach4help/reach4help/876)

*This information is updated automatically. To modify it, please use ZenHub.*

**Belonging to Epics:**

* **[EPIC]** [#881 - [EPIC] New Marketing Push](https://github.com/reach4help/reach4help/issues/881)

**Children:**

* [ ] [#878 - Publish one more article to Medium to make a Publication](https://github.com/reach4help/reach4help/issues/878)
* [ ] [#879 - Start a series on partners who have helped us](https://github.com/reach4help/reach4help/issues/879)
* [ ] [#880 - Start a series on those we have helped](https://github.com/reach4help/reach4help/issues/880)
