### ISSUE TITLE
[EPIC] New Marketing Push

### ISSUE THREAD

**Issue by schowdhury8** [reach4help/reach4help#881]
--------
### [ZenHub Information](https://app.zenhub.com/workspaces/reach4help-5e8dcbfb14ac087f410cbabb/issues/reach4help/reach4help/881)

*This information is updated automatically. To modify it, please use ZenHub.*

**Children:**

* [ ] [[@s0](https://github.com/s0), [@schowdhury8](https://github.com/schowdhury8), [@PatriciaMiranda](https://github.com/PatriciaMiranda)] [#232 - Make a legit marketing video](https://github.com/reach4help/reach4help/issues/232)
* [x] ~~[#661 - Make a video showcasing core app functionality for marketing](https://github.com/reach4help/reach4help/issues/661)~~
* [ ] [[@cinthyaejh](https://github.com/cinthyaejh), [@PatriciaMiranda](https://github.com/PatriciaMiranda)] [#875 - Update social medias with new progress and v2.2.0 release](https://github.com/reach4help/reach4help/issues/875)
* [ ] **[EPIC]** [[@schowdhury8](https://github.com/schowdhury8), [@PatriciaMiranda](https://github.com/PatriciaMiranda)] [#876 - Publish articles to Medium ](https://github.com/reach4help/reach4help/issues/876)
  * [ ] [#878 - Publish one more article to Medium to make a Publication](https://github.com/reach4help/reach4help/issues/878)
  * [ ] [#879 - Start a series on partners who have helped us](https://github.com/reach4help/reach4help/issues/879)
  * [ ] [#880 - Start a series on those we have helped](https://github.com/reach4help/reach4help/issues/880)
* [ ] [#883 - Set up TikTok for P2P marketing](https://github.com/reach4help/reach4help/issues/883)
* [ ] [[@schowdhury8](https://github.com/schowdhury8)] [#884 - Set up Google Adsense with The Programming Foundation](https://github.com/reach4help/reach4help/issues/884)
