### ISSUE TITLE
Map Page

### ISSUE THREAD

**Issue by Apfx1945** [reach4help/reach4help#904]
The Epic for all Landing Page User Stories

--------
### [ZenHub Information](https://app.zenhub.com/workspaces/reach4help-5e8dcbfb14ac087f410cbabb/issues/reach4help/reach4help/904)

*This information is updated automatically. To modify it, please use ZenHub.*

**Belonging to Epics:**

* ~~**[EPIC]** [#915 - v3 Features](https://github.com/reach4help/reach4help/issues/915)~~

**Children:**

* [x] ~~**[EPIC]** [#905 - 4.1 As an unauthenticated user, I want to see requests on a map, so that I can check them out. ](https://github.com/reach4help/reach4help/issues/905)~~
  * [x] ~~[#924 - 4.1.1 Change styling of existing dashboard layout to that of new dashboard layout.](https://github.com/reach4help/reach4help/issues/924)~~
  * [ ] [[@ashwinkjoseph](https://github.com/ashwinkjoseph)] [#925 - 4.1.2 Create a cloud function to generate a restricted search API key (Algolia).](https://github.com/reach4help/reach4help/issues/925)
  * [x] ~~[#926 - 4.1.3 Write action creators in the auth redux module to store search key](https://github.com/reach4help/reach4help/issues/926)~~
  * [x] ~~[#927 - 4.1.4 Refactor Requests Page](https://github.com/reach4help/reach4help/issues/927)~~
* [x] ~~[#906 - 4.3 As an unauthenticated user, I must be taken through the sign in/sign up flow when I try to create a request](https://github.com/reach4help/reach4help/issues/906)~~
* [x] ~~[#907 - 4.9 As an unauthenticated user, I must be taken through the sign in/sign up flow when I try to make an offer for an existing request](https://github.com/reach4help/reach4help/issues/907)~~
* [ ] [#908 - 4.4 As an authenticated user, I want to see requests on a map, so that I can decide which of them I want to help](https://github.com/reach4help/reach4help/issues/908)
* [ ] [#909 - 4.6 As an authenticated user, I want to create a request](https://github.com/reach4help/reach4help/issues/909)
