### ISSUE TITLE
4.1 As an unauthenticated user, I want to see requests on a map, so that I can check them out. 

### ISSUE THREAD

**Issue by Apfx1945** [reach4help/reach4help#905]
As an unauthenticated user, I want to see requests on a map, so that I can check them out. 

Acceptance Criteria:

- Verify that a new component shows up when the user clicks a request. 

- The title, description, and type of request (delivery or other) of the selected request are the only information that shows up on the pop-up.  

Subtasks:
1. https://github.com/reach4help/reach4help/issues/924
2. https://github.com/reach4help/reach4help/issues/925
3. https://github.com/reach4help/reach4help/issues/926
4. https://github.com/reach4help/reach4help/issues/927

--------
### [ZenHub Information](https://app.zenhub.com/workspaces/reach4help-5e8dcbfb14ac087f410cbabb/issues/reach4help/reach4help/905)

*This information is updated automatically. To modify it, please use ZenHub.*

**Belonging to Epics:**

* **[EPIC]** [#904 - Landing Page](https://github.com/reach4help/reach4help/issues/904)

--------
### [ZenHub Information](https://app.zenhub.com/workspaces/reach4help-5e8dcbfb14ac087f410cbabb/issues/reach4help/reach4help/905)

*This information is updated automatically. To modify it, please use ZenHub.*

**Belonging to Epics:**

* **[EPIC]** [#904 - Map Page](https://github.com/reach4help/reach4help/issues/904)

**Children:**

* [x] ~~[#924 - 4.1.1 Change styling of existing dashboard layout to that of new dashboard layout.](https://github.com/reach4help/reach4help/issues/924)~~
* [ ] [[@ashwinkjoseph](https://github.com/ashwinkjoseph)] [#925 - 4.1.2 Create a cloud function to generate a restricted search API key (Algolia).](https://github.com/reach4help/reach4help/issues/925)
* [ ] [[@alexjball](https://github.com/alexjball)] [#926 - 4.1.3 Write action creators in the auth redux module to store search key](https://github.com/reach4help/reach4help/issues/926)
* [ ] [[@alexjball](https://github.com/alexjball)] [#927 - 4.1.4 Refactor Requests Page](https://github.com/reach4help/reach4help/issues/927)

**Comment by vignesh-manel** [comment]
Hi, I would like to work on this issue as well!

**Comment by gilwong00** [comment]
I would also like to work on this issue. Do we spilt the work or should i pick another issue?

**Comment by puzzledbytheweb** [comment]
> I would also like to work on this issue. Do we spilt the work or should i pick another issue?

Hey! I think we should start by splitting the work. I'd say I can have the Cloud function and the redux logic, @vignesh-manel  and you can take the React stuff 4.x. If I finish the cloud function and redux early I jump in to help you guys with React. What do you think?

**Comment by puzzledbytheweb** [comment]
Bulletpoint 1 is done in #923
