### ISSUE TITLE
Authentication and Profile

### ISSUE THREAD

**Issue by Apfx1945** [reach4help/reach4help#910]
The epic for the Authentication and Profile User Stories.

--------
### [ZenHub Information](https://app.zenhub.com/workspaces/reach4help-5e8dcbfb14ac087f410cbabb/issues/reach4help/reach4help/910)

*This information is updated automatically. To modify it, please use ZenHub.*

**Belonging to Epics:**

* ~~**[EPIC]** [#915 - v3 Features](https://github.com/reach4help/reach4help/issues/915)~~

**Children:**

* [x] ~~[#911 - 1.1 As an unauthenticated user, I want to sign up with my social network account, so that I can save time instead of providing my personal data.](https://github.com/reach4help/reach4help/issues/911)~~
* [x] ~~[#912 - 1.2  As an unauthenticated user, I want to sign up with my email address, so that I can have privacy sharing my personal information](https://github.com/reach4help/reach4help/issues/912)~~
* [x] ~~**[EPIC]** [#913 - 1.3 As an authenticated user, I want to modify my personal information on my account](https://github.com/reach4help/reach4help/issues/913)~~
  * [x] ~~[#942 - 1.3.1 Work on top of https://github.com/reach4help/reach4help/tree/feat/1.3](https://github.com/reach4help/reach4help/issues/942)~~
  * [x] ~~[#943 - 1.3.2 Create a new action creator in the profile redux module for uploading a file to firebase storage and storing the downloadURL in the user's profile](https://github.com/reach4help/reach4help/issues/943)~~
  * [x] ~~[#944 - 1.3.3 Create an action creator for deleting the user's profile pic in the profile redux module](https://github.com/reach4help/reach4help/issues/944)~~
  * [x] ~~[#945 - 1.3.4 In the settings page, when the user clicks on the profile picture, open up a pop up modal with the options to delete and to change the profile picture](https://github.com/reach4help/reach4help/issues/945)~~
  * [x] ~~[#946 - 1.3.5 If the user chooses to change the profile picture, allow the user to select a file, then delete the existing profile picture using the action creator from step 3 and then upload the new picture using the action creator from step 2](https://github.com/reach4help/reach4help/issues/946)~~
  * [x] ~~[#947 - 1.3.6 If the user chooses to delete their profile picture, use the action creator from step 3](https://github.com/reach4help/reach4help/issues/947)~~
  * [x] ~~[#948 - 1.3.8 If the user clicks on the change my address option, expand it and show the addresses saved in privilegedInformation modal of the user which can be obtained from the profile state as state.profile.privilegedInformation](https://github.com/reach4help/reach4help/issues/948)~~
  * [x] ~~[#949 - 1.3.7 In the settings page, show the option for change my address as per the design in figma](https://github.com/reach4help/reach4help/issues/949)~~
* [x] ~~[#914 - 1.4 As an authenticated user, I want to be able to delete my account](https://github.com/reach4help/reach4help/issues/914)~~
