### ISSUE TITLE
1.3 As an authenticated user, I want to modify my personal information on my account

### ISSUE THREAD

**Issue by Apfx1945** [reach4help/reach4help#913]
As an authenticated user, I want to modify my personal information on my account.

Acceptance Criteria:

- Verify that the user can modify the name 

- Verify that the user can modify the picture that was uploaded either by Facebook or Google.

- Verify that the user can upload a profile picture if they did not do it at the time of creating the account.

- Verify that the user can modify the profile picture that was uploaded by themselves.

- Verify that the user can see the addresses they saved earlier and edit them (Note that editing a saved address doesn’t mean that the address will be updated in all of the requests that previously used the address)

Technical Details:
1. Work on top of https://github.com/reach4help/reach4help/tree/feat/1.3
2. Create a new action creator in the [profile redux module](https://github.com/reach4help/reach4help/blob/feat/1.3/web-client/src/ducks/profile/actions.ts) for uploading a file to firebase storage and storing the downloadURL in the user's profile
2.a Should accept the file (using File API of browsers) and the an instance of [User model](https://github.com/reach4help/reach4help/blob/feat/1.3/web-client/src/models/users/index.ts) and the user's reference which can be obtained from [`state.profile.userRef`](https://github.com/reach4help/reach4help/blob/feat/1.3/web-client/src/ducks/profile/reducer.ts#L21)
2.b Should [upload the file to firebase storage](https://firebase.google.com/docs/storage/web/upload-files#upload_from_a_blob_or_file) at the path `/{userId}/displayPicture/date.{fileext}` (here `usersId` can be obtained from `state.profile.userRef.id`
2.c Should [obtain the downloadUrl](https://firebase.google.com/docs/storage/web/download-files#download_data_via_url) of the uploaded file
2.d Should assign this URL to the attribute `displayPicture` in the [User model](https://github.com/reach4help/reach4help/blob/feat/1.3/web-client/src/models/users/index.ts)
2.e Save it to firestore at `state.profile.userRef`
3 create an action creator for deleting the user's profile pic in the profile redux module
3.a Should accept the an instance of [User model](https://github.com/reach4help/reach4help/blob/feat/1.3/web-client/src/models/users/index.ts) and the user's reference which can be obtained from [`state.profile.userRef`](https://github.com/reach4help/reach4help/blob/feat/1.3/web-client/src/ducks/profile/reducer.ts#L21)
3.b if the `displayPicture` is a [valid firebase storage URL, create a reference](https://firebase.google.com/docs/storage/web/download-files#create_a_reference) to the firebase storage object and [delete it](https://firebase.google.com/docs/storage/web/delete-files#delete_a_file)
3.c Assign `null` to the attribute `displayPicture` in the [User model](https://github.com/reach4help/reach4help/blob/feat/1.3/web-client/src/models/users/index.ts)
3.d Save it to firestore at `state.profile.userRef`
4. In the [settings page](https://github.com/reach4help/reach4help/blob/feat/1.3/web-client/src/modules/settings/containers/SettingsContainer/SettingsContainer.tsx), when the user clicks on the profile picture, open up a pop up modal with the options to delete and to change the profile picture
5. If the user chooses to change the profile picture, allow the user to select a file, then delete the existing profile picture using the action creator from step 3 and then upload the new picture using the action creator from step 2
6. If the user chooses to delete their profile picture, use the action creator from step 3
7. In the [settings page](https://github.com/reach4help/reach4help/blob/feat/1.3/web-client/src/modules/settings/containers/SettingsContainer/SettingsContainer.tsx), show the option for change my address as per the [design in figma](https://www.figma.com/file/OiU7Tl4k1YFfqZQXxLaRrl/Reach4Help?node-id=4561%3A419)
8. If the user clicks on the change my address option, expand it and show the [addresses saved in privilegedInformation modal](https://github.com/reach4help/reach4help/blob/feat/1.3/web-client/src/models/users/privilegedInformation.ts#L17) of the user which can be obtained from the profile state as [`state.profile.privilegedInformation`](https://github.com/reach4help/reach4help/blob/feat/1.3/web-client/src/ducks/profile/reducer.ts#L20)
8.a The addresses field in privilegedInfromation modal is an object with the keys as the names of the addresses. show the keys in the dropdown and show the appropriate address when a particular address is chosen from the dropdown
8.b by default, try to show the address with the name as `default`, if it isn't found, make an array of the keys and then select the 1st key.
8.c Update the particular address and then update the pirvileged information

--------
### [ZenHub Information](https://app.zenhub.com/workspaces/reach4help-5e8dcbfb14ac087f410cbabb/issues/reach4help/reach4help/913)

*This information is updated automatically. To modify it, please use ZenHub.*

**Belonging to Epics:**

* **[EPIC]** [#910 - Authentication and Profile](https://github.com/reach4help/reach4help/issues/910)

**Children:**

* [ ] [#942 - 1.3.1 Work on top of https://github.com/reach4help/reach4help/tree/feat/1.3](https://github.com/reach4help/reach4help/issues/942)
* [ ] [#943 - 1.3.2 Create a new action creator in the profile redux module for uploading a file to firebase storage and storing the downloadURL in the user's profile](https://github.com/reach4help/reach4help/issues/943)
* [ ] [#944 - 1.3.3 Create an action creator for deleting the user's profile pic in the profile redux module](https://github.com/reach4help/reach4help/issues/944)
* [ ] [#945 - 1.3.4 In the settings page, when the user clicks on the profile picture, open up a pop up modal with the options to delete and to change the profile picture](https://github.com/reach4help/reach4help/issues/945)
* [ ] [#946 - 1.3.5 If the user chooses to change the profile picture, allow the user to select a file, then delete the existing profile picture using the action creator from step 3 and then upload the new picture using the action creator from step 2](https://github.com/reach4help/reach4help/issues/946)
* [ ] [#947 - 1.3.6 If the user chooses to delete their profile picture, use the action creator from step 3](https://github.com/reach4help/reach4help/issues/947)
* [ ] [#948 - 1.3.8 If the user clicks on the change my address option, expand it and show the addresses saved in privilegedInformation modal of the user which can be obtained from the profile state as state.profile.privilegedInformation](https://github.com/reach4help/reach4help/issues/948)
* [ ] [#949 - 1.3.7 In the settings page, show the option for change my address as per the design in figma](https://github.com/reach4help/reach4help/issues/949)

**Comment by schowdhury8** [comment]
@milkrong expressed interest in working on this!
