### ISSUE TITLE
v3 Features

### ISSUE THREAD

**Issue by schowdhury8** [reach4help/reach4help#915]
MOVED TO OUR JIRA SERVER FOR EASIER MANAGEMENT AT [jira.reach4help.org](http://jira.reach4help.org/)
--------

Overview of the features to be rolled out for v3!

Visual design by @r13serra11: https://youtu.be/t3EK5Xrfh24

--------
### [ZenHub Information](https://app.zenhub.com/workspaces/reach4help-5e8dcbfb14ac087f410cbabb/issues/reach4help/reach4help/915)

*This information is updated automatically. To modify it, please use ZenHub.*

**Children:**

* [ ] **[EPIC]** [#904 - Map Page](https://github.com/reach4help/reach4help/issues/904)
  * [ ] **[EPIC]** [[@gilwong00](https://github.com/gilwong00), [@vignesh-manel](https://github.com/vignesh-manel), [@puzzledbytheweb](https://github.com/puzzledbytheweb)] [#905 - 4.1 As an unauthenticated user, I want to see requests on a map, so that I can check them out. ](https://github.com/reach4help/reach4help/issues/905)
    * [x] ~~[#924 - 4.1.1 Change styling of existing dashboard layout to that of new dashboard layout.](https://github.com/reach4help/reach4help/issues/924)~~
    * [ ] [[@ashwinkjoseph](https://github.com/ashwinkjoseph)] [#925 - 4.1.2 Create a cloud function to generate a restricted search API key (Algolia).](https://github.com/reach4help/reach4help/issues/925)
    * [ ] [[@alexjball](https://github.com/alexjball)] [#926 - 4.1.3 Write action creators in the auth redux module to store search key](https://github.com/reach4help/reach4help/issues/926)
    * [ ] [[@alexjball](https://github.com/alexjball)] [#927 - 4.1.4 Refactor Requests Page](https://github.com/reach4help/reach4help/issues/927)
  * [ ] [#906 - 4.3 As an unauthenticated user, I must be taken through the sign in/sign up flow when I try to create a request](https://github.com/reach4help/reach4help/issues/906)
  * [ ] [#907 - 4.9 As an unauthenticated user, I must be taken through the sign in/sign up flow when I try to make an offer for an existing request](https://github.com/reach4help/reach4help/issues/907)
  * [ ] [#908 - 4.4 As an authenticated user, I want to see requests on a map, so that I can decide which of them I want to help](https://github.com/reach4help/reach4help/issues/908)
  * [ ] [#909 - 4.6 As an authenticated user, I want to create a request](https://github.com/reach4help/reach4help/issues/909)
* [ ] **[EPIC]** [#910 - Authentication and Profile](https://github.com/reach4help/reach4help/issues/910)
  * [ ] [[@milkrong](https://github.com/milkrong)] [#911 - 1.1 As an unauthenticated user, I want to sign up with my social network account, so that I can save time instead of providing my personal data.](https://github.com/reach4help/reach4help/issues/911)
  * [ ] [[@milkrong](https://github.com/milkrong)] [#912 - 1.2  As an unauthenticated user, I want to sign up with my email address, so that I can have privacy sharing my personal information](https://github.com/reach4help/reach4help/issues/912)
  * [ ] **[EPIC]** [[@milkrong](https://github.com/milkrong)] [#913 - 1.3 As an authenticated user, I want to modify my personal information on my account](https://github.com/reach4help/reach4help/issues/913)
    * [ ] [#942 - 1.3.1 Work on top of https://github.com/reach4help/reach4help/tree/feat/1.3](https://github.com/reach4help/reach4help/issues/942)
    * [ ] [#943 - 1.3.2 Create a new action creator in the profile redux module for uploading a file to firebase storage and storing the downloadURL in the user's profile](https://github.com/reach4help/reach4help/issues/943)
    * [ ] [#944 - 1.3.3 Create an action creator for deleting the user's profile pic in the profile redux module](https://github.com/reach4help/reach4help/issues/944)
    * [ ] [#945 - 1.3.4 In the settings page, when the user clicks on the profile picture, open up a pop up modal with the options to delete and to change the profile picture](https://github.com/reach4help/reach4help/issues/945)
    * [ ] [#946 - 1.3.5 If the user chooses to change the profile picture, allow the user to select a file, then delete the existing profile picture using the action creator from step 3 and then upload the new picture using the action creator from step 2](https://github.com/reach4help/reach4help/issues/946)
    * [ ] [#947 - 1.3.6 If the user chooses to delete their profile picture, use the action creator from step 3](https://github.com/reach4help/reach4help/issues/947)
    * [ ] [#948 - 1.3.8 If the user clicks on the change my address option, expand it and show the addresses saved in privilegedInformation modal of the user which can be obtained from the profile state as state.profile.privilegedInformation](https://github.com/reach4help/reach4help/issues/948)
    * [ ] [#949 - 1.3.7 In the settings page, show the option for change my address as per the design in figma](https://github.com/reach4help/reach4help/issues/949)
  * [x] ~~[#914 - 1.4 As an authenticated user, I want to be able to delete my account](https://github.com/reach4help/reach4help/issues/914)~~
* [ ] **[EPIC]** [#936 - Requests](https://github.com/reach4help/reach4help/issues/936)
  * [ ] **[EPIC]** **[BLOCKING: [#966](https://github.com/reach4help/reach4help/issues/966)]** **[UNASSIGNED]** [#935 - 2.1 As a PIN, I want to create a request, so that I can reach for help](https://github.com/reach4help/reach4help/issues/935)
    * [x] ~~[#937 - 2.1.1 [TECH]Extract New Request Container into a new module named “Create”](https://github.com/reach4help/reach4help/issues/937)~~
    * [ ] [#938 - 2.1.2 [TECH]Create a component named StepTracker which takes in a step number as it’s prop and would highlight that particular step](https://github.com/reach4help/reach4help/issues/938)
    * [x] ~~[#939 - 2.1.3 [TECH]Create a global component that lets users choose or create a new address and return the chosen/new address as a callback when the user submits. ](https://github.com/reach4help/reach4help/issues/939)~~
    * [ ] [#940 - 2.1.4 Create a new global component named ‘ReviewPage’](https://github.com/reach4help/reach4help/issues/940)
    * [ ] [#941 - 2.1.5 Use these components appropriately to provide the experience shown in figma](https://github.com/reach4help/reach4help/issues/941)
  * [ ] **[EPIC]** [[@Tapudp](https://github.com/Tapudp)] [#968 - 2.5 As a PIN, I want to be able to accept an offer to my request, so that I can choose whether or not I get help from that offer.](https://github.com/reach4help/reach4help/issues/968)
    * [ ] [#969 - 2.5.1 Obtain post Id (currently request Id) from query parameters and read data from firestore directly](https://github.com/reach4help/reach4help/issues/969)
    * [ ] [#970 - 2.5.2 Render loading animation until the request details are loaded ](https://github.com/reach4help/reach4help/issues/970)
    * [ ] [#971 - 2.5.3 If the status of the request is pending and if the current user is the person who made the request, read all the offers from firestore which were made against this request and render them in the offerlist](https://github.com/reach4help/reach4help/issues/971)
    * [ ] [#972 - 2.5.4 Render loading animation at the lower part of the screen (the white area responsible for rendering offer list in figma) until the offers are loaded ](https://github.com/reach4help/reach4help/issues/972)
  * [ ] **[EPIC]** **[BLOCKING: [#981](https://github.com/reach4help/reach4help/issues/981), [#980](https://github.com/reach4help/reach4help/issues/980)]** **[UNASSIGNED]** [#975 - 2.9 As a PIN, I want to be given the CAV's number once they accept my request to their offer, so that I can call them to get better communication](https://github.com/reach4help/reach4help/issues/975)
    * [ ] [#976 - 2.9.1 Obtain the timeline events belonging to the request](https://github.com/reach4help/reach4help/issues/976)
    * [ ] [#977 - 2.9.2 Render the loading animation at the lower part (the white area responsible for rendering the timeline events in figma) while the data is loading for the timeline events](https://github.com/reach4help/reach4help/issues/977)
    * [ ] [#978 - 2.9.3 Write a cloud function to retrieve the phone number of the other person in a post-response  pair](https://github.com/reach4help/reach4help/issues/978)
    * [ ] [#979 - 2.9.4 If the status of the request is ongoing, then show the call/phone icon on top in the top panel and call the firebase function written in the task above to obtain the phone number](https://github.com/reach4help/reach4help/issues/979)
  * [ ] [BLOCKED BY: [#975](https://github.com/reach4help/reach4help/issues/975)] [#980 - 2.8 As a PIN, I want to be given the CAV's number once I accept their offer to my request, so that I can call them to get better communication](https://github.com/reach4help/reach4help/issues/980)
* [ ] **[EPIC]** [#951 - My Requests](https://github.com/reach4help/reach4help/issues/951)
  * [ ] **[EPIC]** **[BLOCKING: [#974](https://github.com/reach4help/reach4help/issues/974), [#982](https://github.com/reach4help/reach4help/issues/982)]** **[UNASSIGNED]** [#950 - 6.1 As a PIN, I want to see and filter all the requests that I have created, so that I can choose among them.](https://github.com/reach4help/reach4help/issues/950)
    * [x] ~~[#955 - 6.1.1 Add seenBy object to the GeneralRequests model](https://github.com/reach4help/reach4help/issues/955)~~
    * [ ] [[@ethanstrominger](https://github.com/ethanstrominger)] [#956 - 6.1.2 Create a new cloud function named markAsSeen that would take the user’s details, and the post details and update the seenBy object in algolia to reflect that the user has seen the post.](https://github.com/reach4help/reach4help/issues/956)
    * [ ] [[@ashwinkjoseph](https://github.com/ashwinkjoseph), [@ethanstrominger](https://github.com/ethanstrominger)] [#957 - 6.1.3 Set up the posts route and module with appropriate urls and the tab view for MyRequests and MyOffers which would have their own URLs but the same route handler](https://github.com/reach4help/reach4help/issues/957)
    * [ ] [[@ashwinkjoseph](https://github.com/ashwinkjoseph)] [#958 - 6.1.4 When the user opens the MyRequests tab, it should use the instantsearch SDK to fetch all the posts from GeneralRequests Index using the SDK while using the filters option in algolia search to retrieve only the posts the user has created with the type as ask](https://github.com/reach4help/reach4help/issues/958)
    * [ ] [#959 - 6.1.5 Make a component named filter which would provide a dropdown with different statuses for the request, when the user clicks on any of the filters, it must refetch data from algolia with the additional filter for the status](https://github.com/reach4help/reach4help/issues/959)
    * [ ] [#960 - 6.1.6 Modify the requestItem component to accept the participants, creator, status, alert, details all separately and render them as per design (also rename this to postItem)](https://github.com/reach4help/reach4help/issues/960)
    * [ ] [#961 - 6.1.7 Create a callback function named onOpen which would accept the id of the post and would call the udpateNotified cloud function markAsSeen](https://github.com/reach4help/reach4help/issues/961)
    * [ ] [#962 - 6.1.8 Render the list of posts obtained from algolia using the requestItem component](https://github.com/reach4help/reach4help/issues/962)
    * [ ] [[@ashwinkjoseph](https://github.com/ashwinkjoseph)] [#963 - 6.1.9 When the timeline page (or the request details page) is opened, instead of calling retrieving all requests, fetch data from firestore sequentially](https://github.com/reach4help/reach4help/issues/963)
  * [ ] [BLOCKED BY: [#950](https://github.com/reach4help/reach4help/issues/950)] [#982 - 6.3 As a PIN, I want to review all my ongoing and closed request](https://github.com/reach4help/reach4help/issues/982)
* [ ] **[EPIC]** [#967 - Offers ](https://github.com/reach4help/reach4help/issues/967)
  * [ ] **[EPIC]** [BLOCKED BY: [#935](https://github.com/reach4help/reach4help/issues/935)] [#966 - 3.6 Add the ability to create an offer for requests, so a CAV can help requests that have already been set. (CAV)](https://github.com/reach4help/reach4help/issues/966)
  * [ ] [BLOCKED BY: [#975](https://github.com/reach4help/reach4help/issues/975)] [#981 - 3.10 As a CAV, I want to be given the PIN's number once they accept my offer to their request, so that I can call them to get better communication](https://github.com/reach4help/reach4help/issues/981)
* [ ] **[EPIC]** [#973 - My offers](https://github.com/reach4help/reach4help/issues/973)
  * [ ] [BLOCKED BY: [#950](https://github.com/reach4help/reach4help/issues/950)] [#974 - 7.2 As a CAV, I want to see and filter all the requests that I offered help, so that I can choose among them](https://github.com/reach4help/reach4help/issues/974)
