### ISSUE TITLE
2.1 As a PIN, I want to create a request, so that I can reach for help

### ISSUE THREAD

**Issue by gorostiaga** [reach4help/reach4help#935]
**Acceptance Criteria**

- [ ] - Make sure that the PIN introduces a name of request and a description of the request. 
- [ ] - Once the user has put all the required information, they have a button to confirm the request. 
- [ ] - Make sure that all the mandatory information is given. 

--------
### [ZenHub Information](https://app.zenhub.com/workspaces/reach4help-5e8dcbfb14ac087f410cbabb/issues/reach4help/reach4help/935)

*This information is updated automatically. To modify it, please use ZenHub.*

**Belonging to Epics:**

* **[EPIC]** [#936 - Requests](https://github.com/reach4help/reach4help/issues/936)

**Blocking:**

* **[EPIC]** [BLOCKED BY: [#935](https://github.com/reach4help/reach4help/issues/935)] [#935 - 3.6 Add the ability to create an offer for requests, so a CAV can help requests that have already been set. (CAV)](https://github.com/reach4help/reach4help/issues/966)

**Children:**

* [x] ~~[#937 - 2.1.1 [TECH]Extract New Request Container into a new module named “Create”](https://github.com/reach4help/reach4help/issues/937)~~
* [ ] [#938 - 2.1.2 [TECH]Create a component named StepTracker which takes in a step number as it’s prop and would highlight that particular step](https://github.com/reach4help/reach4help/issues/938)
* [x] ~~[#939 - 2.1.3 [TECH]Create a global component that lets users choose or create a new address and return the chosen/new address as a callback when the user submits. ](https://github.com/reach4help/reach4help/issues/939)~~
* [ ] [#940 - 2.1.4 Create a new global component named ‘ReviewPage’](https://github.com/reach4help/reach4help/issues/940)
* [ ] [#941 - 2.1.5 Use these components appropriately to provide the experience shown in figma](https://github.com/reach4help/reach4help/issues/941)
