### ISSUE TITLE
Requests

### ISSUE THREAD

**Issue by gorostiaga** [reach4help/reach4help#936]
It is a set of User Stories related to requests 

--------
### [ZenHub Information](https://app.zenhub.com/workspaces/reach4help-5e8dcbfb14ac087f410cbabb/issues/reach4help/reach4help/936)

*This information is updated automatically. To modify it, please use ZenHub.*

**Belonging to Epics:**

* ~~**[EPIC]** [#915 - v3 Features](https://github.com/reach4help/reach4help/issues/915)~~

**Children:**

* [x] ~~**[EPIC]** [#935 - 2.1 As a PIN, I want to create a request, so that I can reach for help](https://github.com/reach4help/reach4help/issues/935)~~
  * [x] ~~[#937 - 2.1.1 [TECH]Extract New Request Container into a new module named “Create”](https://github.com/reach4help/reach4help/issues/937)~~
  * [ ] [#938 - 2.1.2 [TECH]Create a component named StepTracker which takes in a step number as it’s prop and would highlight that particular step](https://github.com/reach4help/reach4help/issues/938)
  * [x] ~~[#939 - 2.1.3 [TECH]Create a global component that lets users choose or create a new address and return the chosen/new address as a callback when the user submits. ](https://github.com/reach4help/reach4help/issues/939)~~
  * [ ] [#940 - 2.1.4 Create a new global component named ‘ReviewPage’](https://github.com/reach4help/reach4help/issues/940)
  * [x] ~~[#941 - 2.1.5 Use these components appropriately to provide the experience shown in figma](https://github.com/reach4help/reach4help/issues/941)~~
* [x] ~~**[EPIC]** [#968 - 2.5 As a PIN, I want to be able to accept an offer to my request, so that I can choose whether or not I get help from that offer.](https://github.com/reach4help/reach4help/issues/968)~~
  * [x] ~~[#969 - 2.5.1 Obtain post Id (currently request Id) from query parameters and read data from firestore directly](https://github.com/reach4help/reach4help/issues/969)~~
  * [x] ~~[#970 - 2.5.2 Render loading animation until the request details are loaded ](https://github.com/reach4help/reach4help/issues/970)~~
  * [x] ~~[#971 - 2.5.3 If the status of the request is pending and if the current user is the person who made the request, read all the offers from firestore which were made against this request and render them in the offerlist](https://github.com/reach4help/reach4help/issues/971)~~
  * [x] ~~[#972 - 2.5.4 Render loading animation at the lower part of the screen (the white area responsible for rendering offer list in figma) until the offers are loaded ](https://github.com/reach4help/reach4help/issues/972)~~
* [x] ~~**[EPIC]** [#975 - 2.9 As a PIN, I want to be given the CAV's number once they accept my request to their offer, so that I can call them to get better communication](https://github.com/reach4help/reach4help/issues/975)~~
  * [x] ~~[#976 - 2.9.1 Obtain the timeline events belonging to the request](https://github.com/reach4help/reach4help/issues/976)~~
  * [x] ~~[#977 - 2.9.2 Render the loading animation at the lower part (the white area responsible for rendering the timeline events in figma) while the data is loading for the timeline events](https://github.com/reach4help/reach4help/issues/977)~~
  * [x] ~~[#978 - 2.9.3 Write a cloud function to retrieve the phone number of the other person in a post-response  pair](https://github.com/reach4help/reach4help/issues/978)~~
  * [x] ~~[#979 - 2.9.4 If the status of the request is ongoing, then show the call/phone icon on top in the top panel and call the firebase function written in the task above to obtain the phone number](https://github.com/reach4help/reach4help/issues/979)~~
* [x] ~~[#980 - 2.8 As a PIN, I want to be given the CAV's number once I accept their offer to my request, so that I can call them to get better communication](https://github.com/reach4help/reach4help/issues/980)~~

**Comment by schowdhury8** [comment]
Thanks so much for all this, Javier! Just to keep track...
@all-contributors please add @gorostiaga for project management and ideas!
