### ISSUE TITLE
6.1 As a PIN, I want to see and filter all the requests that I have created, so that I can choose among them.

### ISSUE THREAD

**Issue by gorostiaga** [reach4help/reach4help#950]
--------
### [ZenHub Information](https://app.zenhub.com/workspaces/reach4help-5e8dcbfb14ac087f410cbabb/issues/reach4help/reach4help/950)

*This information is updated automatically. To modify it, please use ZenHub.*

**Belonging to Epics:**

* **[EPIC]** [#951 - My Requests](https://github.com/reach4help/reach4help/issues/951)

**Blocking:**

* [BLOCKED BY: [#950](https://github.com/reach4help/reach4help/issues/950)] [#950 - 7.2 As a CAV, I want to see and filter all the requests that I offered help, so that I can choose among them](https://github.com/reach4help/reach4help/issues/974)
* [BLOCKED BY: [#950](https://github.com/reach4help/reach4help/issues/950)] [#950 - 6.3 As a PIN, I want to review all my ongoing and closed request](https://github.com/reach4help/reach4help/issues/982)

**Children:**

* [x] ~~[#955 - 6.1.1 Add seenBy object to the GeneralRequests model](https://github.com/reach4help/reach4help/issues/955)~~
* [ ] [[@ethanstrominger](https://github.com/ethanstrominger)] [#956 - 6.1.2 Create a new cloud function named markAsSeen that would take the user’s details, and the post details and update the seenBy object in algolia to reflect that the user has seen the post.](https://github.com/reach4help/reach4help/issues/956)
* [ ] [[@ashwinkjoseph](https://github.com/ashwinkjoseph), [@ethanstrominger](https://github.com/ethanstrominger)] [#957 - 6.1.3 Set up the posts route and module with appropriate urls and the tab view for MyRequests and MyOffers which would have their own URLs but the same route handler](https://github.com/reach4help/reach4help/issues/957)
* [ ] [[@ashwinkjoseph](https://github.com/ashwinkjoseph)] [#958 - 6.1.4 When the user opens the MyRequests tab, it should use the instantsearch SDK to fetch all the posts from GeneralRequests Index using the SDK while using the filters option in algolia search to retrieve only the posts the user has created with the type as ask](https://github.com/reach4help/reach4help/issues/958)
* [ ] [#959 - 6.1.5 Make a component named filter which would provide a dropdown with different statuses for the request, when the user clicks on any of the filters, it must refetch data from algolia with the additional filter for the status](https://github.com/reach4help/reach4help/issues/959)
* [ ] [#960 - 6.1.6 Modify the requestItem component to accept the participants, creator, status, alert, details all separately and render them as per design (also rename this to postItem)](https://github.com/reach4help/reach4help/issues/960)
* [ ] [#961 - 6.1.7 Create a callback function named onOpen which would accept the id of the post and would call the udpateNotified cloud function markAsSeen](https://github.com/reach4help/reach4help/issues/961)
* [ ] [#962 - 6.1.8 Render the list of posts obtained from algolia using the requestItem component](https://github.com/reach4help/reach4help/issues/962)
* [ ] [[@ashwinkjoseph](https://github.com/ashwinkjoseph)] [#963 - 6.1.9 When the timeline page (or the request details page) is opened, instead of calling retrieving all requests, fetch data from firestore sequentially](https://github.com/reach4help/reach4help/issues/963)
