### ISSUE TITLE
3.6 Add the ability to create an offer for requests, so a CAV can help requests that have already been set. (CAV)

### ISSUE THREAD

**Issue by gorostiaga** [reach4help/reach4help#966]
**Acceptance Criteria:**

- [ ] The user has to put an address (new or saved) in the form for offering help.
- [ ] The user has to be able to see a list of requests.
- [ ] The user has to be able to check requests from the list.
- [ ] The user has to have the option pick a request and send an offer through a button "offer help" next to the request.

This User Story does not need a sub task. The required actions are:
Should use the components created from https://github.com/reach4help/reach4help/issues/939 and https://github.com/reach4help/reach4help/issues/940 to create the flow for creating a response as shown here in figma: https://www.figma.com/file/OiU7Tl4k1YFfqZQXxLaRrl/Reach4Help?node-id=4556%3A4135

Dependency: https://github.com/reach4help/reach4help/issues/935

--------
### [ZenHub Information](https://app.zenhub.com/workspaces/reach4help-5e8dcbfb14ac087f410cbabb/issues/reach4help/reach4help/966)

*This information is updated automatically. To modify it, please use ZenHub.*

**Belonging to Epics:**

* **[EPIC]** [#967 - Offers ](https://github.com/reach4help/reach4help/issues/967)

**Children:**

--------
### [ZenHub Information](https://app.zenhub.com/workspaces/reach4help-5e8dcbfb14ac087f410cbabb/issues/reach4help/reach4help/966)

*This information is updated automatically. To modify it, please use ZenHub.*

**Belonging to Epics:**

* **[EPIC]** [#967 - Offers ](https://github.com/reach4help/reach4help/issues/967)

**Blocked By:**

* **[EPIC]** **[BLOCKING: [#966](https://github.com/reach4help/reach4help/issues/966)]** **[UNASSIGNED]** [#966 - 2.1 As a PIN, I want to create a request, so that I can reach for help](https://github.com/reach4help/reach4help/issues/935)

**Children:**
