### ISSUE TITLE
2.5 As a PIN, I want to be able to accept an offer to my request, so that I can choose whether or not I get help from that offer.

### ISSUE THREAD

**Issue by gorostiaga** [reach4help/reach4help#968]
**Acceptance Criteria**

- [ ] All offers for that request have to be listed inside the field of the request. 
- [ ] There has to be 2 buttons "reject" and "accept" next to the offer for the request. 
- [ ] Make sure that the old feature is refactored with theses requirements

--------
### [ZenHub Information](https://app.zenhub.com/workspaces/reach4help-5e8dcbfb14ac087f410cbabb/issues/reach4help/reach4help/968)

*This information is updated automatically. To modify it, please use ZenHub.*

**Belonging to Epics:**

* **[EPIC]** [#936 - Requests](https://github.com/reach4help/reach4help/issues/936)

**Children:**

* [ ] [#969 - 2.5.1 Obtain post Id (currently request Id) from query parameters and read data from firestore directly](https://github.com/reach4help/reach4help/issues/969)
* [ ] [#970 - 2.5.2 Render loading animation until the request details are loaded ](https://github.com/reach4help/reach4help/issues/970)
* [ ] [#971 - 2.5.3 If the status of the request is pending and if the current user is the person who made the request, read all the offers from firestore which were made against this request and render them in the offerlist](https://github.com/reach4help/reach4help/issues/971)
* [ ] [#972 - 2.5.4 Render loading animation at the lower part of the screen (the white area responsible for rendering offer list in figma) until the offers are loaded ](https://github.com/reach4help/reach4help/issues/972)
