### ISSUE TITLE
2.9 As a PIN, I want to be given the CAV's number once they accept my request to their offer, so that I can call them to get better communication

### ISSUE THREAD

**Issue by gorostiaga** [reach4help/reach4help#975]
This should be completed after https://github.com/reach4help/reach4help/issues/968 is done when the status of the request is either ongoing or the current user is not the person who made the request

**Dependecy**: https://github.com/reach4help/reach4help/issues/968

--------
### [ZenHub Information](https://app.zenhub.com/workspaces/reach4help-5e8dcbfb14ac087f410cbabb/issues/reach4help/reach4help/975)

*This information is updated automatically. To modify it, please use ZenHub.*

**Belonging to Epics:**

* **[EPIC]** [#936 - Requests](https://github.com/reach4help/reach4help/issues/936)

**Blocking:**

* [BLOCKED BY: [#975](https://github.com/reach4help/reach4help/issues/975)] [#975 - 3.10 As a CAV, I want to be given the PIN's number once they accept my offer to their request, so that I can call them to get better communication](https://github.com/reach4help/reach4help/issues/981)
* [BLOCKED BY: [#975](https://github.com/reach4help/reach4help/issues/975)] [#975 - 2.8 As a PIN, I want to be given the CAV's number once I accept their offer to my request, so that I can call them to get better communication](https://github.com/reach4help/reach4help/issues/980)

**Children:**

* [ ] [#976 - 2.9.1 Obtain the timeline events belonging to the request](https://github.com/reach4help/reach4help/issues/976)
* [ ] [#977 - 2.9.2 Render the loading animation at the lower part (the white area responsible for rendering the timeline events in figma) while the data is loading for the timeline events](https://github.com/reach4help/reach4help/issues/977)
* [ ] [#978 - 2.9.3 Write a cloud function to retrieve the phone number of the other person in a post-response  pair](https://github.com/reach4help/reach4help/issues/978)
* [ ] [#979 - 2.9.4 If the status of the request is ongoing, then show the call/phone icon on top in the top panel and call the firebase function written in the task above to obtain the phone number](https://github.com/reach4help/reach4help/issues/979)
